# Use the official Node.js 14 image
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app's source code
COPY . .

# Expose port 8081
EXPOSE 8081

# Start the Node.js app
CMD ["npm", "run", "start"]
